string sqlQuery = "INSERT INTO BCAH96DTA.UTH01CCC (CCC00GUID, CCC01CORR, CCC02FECH, CCC03HORA, CCC04CAJE, CCC05BANC, CCC06SUCU, CCC07TERM, CCC08LIMI, CCC09NTOK, CCC10STAT, CCC11MESS, CCC12DTID, CCC12DTNA, CCC13DTPO, CCC13TIST, CCC14MDTI, CCC15MDHM, CCC16MDNT, CCC17COVA, CCC18CONA, CCC19ERRO, CCC20MENS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
using var command = _connection.GetDbCommand(_contextAccessor.HttpContext!);
command.CommandText = sqlQuery;

command.CommandType = System.Data.CommandType.Text;
command.Parameters.Add("CCC00GUID", OleDbType.Char).Value = getCompaniesDto.CamposObligatoriosModel.Guid;
command.Parameters.Add("CCC01CORR", OleDbType.Char).Value = correlativo.ToString();
command.Parameters.Add("CCC02FECH", OleDbType.Char).Value = getCompaniesDto.CamposObligatoriosModel.Fecha;
command.Parameters.Add("CCC03HORA", OleDbType.Char).Value = getCompaniesDto.CamposObligatoriosModel.Hora;
command.Parameters.Add("CCC04CAJE", OleDbType.Char).Value = getCompaniesDto.CamposObligatoriosModel.Cajero;
command.Parameters.Add("CCC05BANC", OleDbType.Char).Value = getCompaniesDto.CamposObligatoriosModel.Banco;
command.Parameters.Add("CCC06SUCU", OleDbType.Char).Value = getCompaniesDto.CamposObligatoriosModel.Sucursal;
command.Parameters.Add("CCC07TERM", OleDbType.Char).Value = getCompaniesDto.CamposObligatoriosModel.Terminal;
command.Parameters.Add("CCC08LIMI", OleDbType.Char).Value = getCompaniesDto.Limit;
command.Parameters.Add("CCC09NTOK", OleDbType.Char).Value = getCompaniesDto.NextToken;
command.Parameters.Add("CCC10STAT", OleDbType.Char).Value = list2.Status;
command.Parameters.Add("CCC11MESS", OleDbType.Char).Value = list2.Message;
command.Parameters.Add("CCC12DTID", OleDbType.Char).Value = list3.Id;
command.Parameters.Add("CCC12DTNA", OleDbType.Char).Value = list3.Name;
command.Parameters.Add("CCC13DTPO", OleDbType.Char).Value = (list3.PayableOptions == null) ? "Nulo" : string.Join(",", list3.PayableOptions);
command.Parameters.Add("CCC13TIST", OleDbType.Char).Value = list2.Timestamp.ToString();
command.Parameters.Add("CCC14MDTI", OleDbType.Char).Value = list2.Metadata.Items;
command.Parameters.Add("CCC15MDHM", OleDbType.Char).Value = ((list2.Metadata.HasMore.ToString() == null) ? "NO" : list2.Metadata.HasMore.ToString());
command.Parameters.Add("CCC16MDNT", OleDbType.Char).Value = ((list2.Metadata.NextToken == null) ? "" : list2.Metadata.NextToken);
command.Parameters.Add("CCC17COVA", OleDbType.Char).Value = ((list2.Code.Value.ToString() == null) ? "124" : list2.Code.Value.ToString());
command.Parameters.Add("CCC18CONA", OleDbType.Char).Value = ((list2.Code.Name == null) ? "" : list2.Code.Name);
command.Parameters.Add("CCC19ERRO", OleDbType.Char).Value = getCompaniesResponseDto.Error;
command.Parameters.Add("CCC20MENS", OleDbType.Char).Value = ((getCompaniesResponseDto.Mensaje == null) ? "Proceso ejecutado Satisfactoriamente" : getCompaniesResponseDto.Mensaje);

command.ExecuteNonQuery();
