SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    LENGTH,
    NUMERIC_SCALE AS SCALE,
    IS_NULLABLE,
    COLUMN_TEXT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'BCAH96DTA'
  AND TABLE_NAME = 'ADQCTL'
ORDER BY ORDINAL_POSITION;
