MERGE INTO IADQFUXU AS tgt
USING (
    SELECT ADQFUCO
    FROM IADQFUXU
    WHERE ADQPECO = 'TLORTEGA2'
) AS src
ON  tgt.ADQPECO = 'TBBANEGA1'
AND tgt.ADQFUCO = src.ADQFUCO
WHEN NOT MATCHED THEN
  INSERT (ADQPECO, ADQFUCO)
  VALUES ('TBBANEGA1', src.ADQFUCO);
